### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by bitsofinfo** [sheelc/dbaisummit-2021-json-talk#1]
Hi - I found this talk pretty interesting, thanks! Is the video available anywhere else?

**Comment by sheelc** [comment]
Awesome, thanks for stopping by! The organizers said the talk recording should be available soon, so I'll update here with a link when available.

**Comment by sheelc** [comment]
Looks like the recordings are available on dataaisummit.com but do require logging in. If you have a login, here's a [direct link](https://dataaisummit.com/session-virtual/?v26dd132ae80017cdaf764437c30ebe6f10c1b1eeaab01165e44366654b368dfaeab6baf7e386a642ecb238989334530e=1EE56F909ADDEC99F0C6A973C8F96D1D21928042B33F2B98E1D208AB3C5F92244C5AE61CEAE487DAEF95FC9F847015A2)!

Perhaps the team will move them over to somewhere not requiring conference registration after a few more weeks.
